nome = str(input("\nEntre com nome: "))
endereco = str(input("\nEntre com endereço: "))
telefone = str(input("\nEntre com telefone: "))
print("\n\n\n")
print(f"\nNome: {nome}")
print(f"\nEndereço: {endereco}")
print(f"\nTelefone: {telefone}")
print("\n")